server:
  port: 8000
  servlet:
    context-path: /web-form
spring:
  datasource:
    url: jdbc:h2:file:./data/db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: azor
    password: azor
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  sql:
    init:
      mode: never